services:
    kassner.auth.controller_listener:
        class: Kassner\AuthBundle\Security\ControllerListener
        arguments: [ @annotation_reader, @security.context ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    kassner.auth.voter:
        class: Kassner\AuthBundle\Security\Voter
        public: false
        tags:
            - { name: security.voter }