security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha1
        Kassner\AuthBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    providers:
        main:
            entity:
                class: Kassner\AuthBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        translations:
            pattern: ^/translations
            security: false

        login:
            pattern:  ^/auth/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: auth_login_check
                login_path: auth_login
            logout:
                path:   auth_logout
                target: home
